Fix `AttributeError: 'NoneType' object has no attribute 'copy'` caused by not immediately returning for user rows that were previously filtered out, as per 5a5a041d098bff6f584499a0a3154c02f9b1530b